package scanners

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/draugr-dev/draugr/pkg/plugin"
)

// mendSettings2 is one scan's resolved configuration: what the descriptor said, plus the
// credentials the environment holds.
//
// The split is deliberate and is the whole reason this type exists. A product token identifies a
// product and authenticates nothing, so it belongs in the descriptor where it can differ per
// component and be reviewed. A user key authenticates everything, so it never appears there.
type mendSettings2 struct {
	url          string
	userKey      string
	productToken string
	project      string
	// agentSettings are passed to the Unified Agent verbatim. Not a curated subset: what the
	// agent discovers depends entirely on how each ecosystem's package manager was told to run,
	// curating would mean tracking every ecosystem Mend supports and lagging behind it, and the
	// people running this already know these keys from their own Mend setup.
	agentSettings map[string]string
	// excludes are derived from the component's scope rather than configured, because Draugr
	// already knows what the component does not include.
	excludes      []string
	resultTimeout time.Duration
}

// mendSettings resolves a scan's configuration, or explains what is missing.
func mendSettings(cfg plugin.Config, env func(string) string) (mendSettings2, error) {
	s := mendSettings2{
		url:           strings.TrimRight(env(envMendURL), "/"),
		userKey:       env(envMendUserKey),
		resultTimeout: defaultResultTimeout,
		agentSettings: map[string]string{},
	}
	var missing []string
	if s.url == "" {
		missing = append(missing, envMendURL)
	}
	if s.userKey == "" {
		missing = append(missing, envMendUserKey)
	}
	if env(envMendEmail) == "" {
		missing = append(missing, envMendEmail)
	}
	if len(missing) > 0 {
		return mendSettings2{}, fmt.Errorf(
			"mend: %s not set. Mend credentials come from the environment rather than the "+
				"descriptor, because a Saga is committed and reviewed and a key is not",
			strings.Join(missing, ", "))
	}

	if v, ok := cfg["productToken"].(string); ok && v != "" {
		s.productToken = v
	} else {
		return mendSettings2{}, fmt.Errorf(
			"mend: controllers.sca.mendSca.productToken is required — it names the Mend product " +
				"this component reports into. It identifies a product and grants nothing, so it " +
				"belongs in the descriptor")
	}
	if v, ok := cfg["project"].(string); ok && v != "" {
		s.project = v
	}
	if v, ok := cfg["resultTimeout"].(string); ok && v != "" {
		d, err := time.ParseDuration(v)
		if err != nil {
			return mendSettings2{}, fmt.Errorf("mend: resultTimeout %q is not a duration (e.g. \"15m\"): %w", v, err)
		}
		s.resultTimeout = d
	}
	for k, v := range mapOf(cfg["settings"]) {
		s.agentSettings[k] = fmt.Sprint(v)
	}
	return s, nil
}

// mapOf reads a nested config block, whatever shape the decoder produced.
func mapOf(v any) map[string]any {
	switch m := v.(type) {
	case map[string]any:
		return m
	case map[any]any:
		out := make(map[string]any, len(m))
		for k, val := range m {
			out[fmt.Sprint(k)] = val
		}
		return out
	}
	return nil
}

// agentConfig renders the Unified Agent configuration for one scan.
//
// Draugr supplies only what it owns — the exclusions implied by the component's scope — and the
// operator's settings are written after, so a descriptor can override anything here.
func (s mendSettings2) agentConfig() string {
	var b strings.Builder
	b.WriteString("# Generated by Draugr for one scan. Edits here do not survive it;\n")
	b.WriteString("# set controllers.sca.mendSca.settings in the Saga instead.\n")
	if len(s.excludes) > 0 {
		b.WriteString("excludes=" + strings.Join(s.excludes, " ") + "\n")
	}
	keys := make([]string, 0, len(s.agentSettings))
	for k := range s.agentSettings {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(k + "=" + s.agentSettings[k] + "\n")
	}
	return b.String()
}
