package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

type initOptions struct {
	output string
	force  bool
}

func newInitCommand() *cobra.Command {
	opts := &initOptions{}
	cmd := &cobra.Command{
		Use:   "init [dir]",
		Short: "Scaffold a draugr.saga.yaml for the current project",
		Long: "Write a starter Saga for the given directory (default: the current one),\n" +
			"detecting the stack to pre-fill sensible controls. Edit it, then `draugr scan`.\n" +
			"For an instant scan with no file, use `draugr scan .` instead.",
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			return runInit(dir, *opts, cmd.OutOrStdout())
		},
	}
	cmd.Flags().StringVarP(&opts.output, "output", "o", "draugr.saga.yaml", "path to write the Saga (- for stdout)")
	cmd.Flags().BoolVarP(&opts.force, "force", "f", false, "overwrite an existing file")
	return cmd
}

// runInit scaffolds a Saga for dir, writing it to opts.output (or stdout).
func runInit(dir string, opts initOptions, w io.Writer) error {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	name := filepath.Base(abs)
	if name == "" || name == "." || name == string(filepath.Separator) {
		name = "app"
	}
	saga := scaffoldSaga(dir, name)

	if opts.output == "-" {
		_, err := io.WriteString(w, saga)
		return err
	}
	if !opts.force {
		if _, err := os.Stat(opts.output); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", opts.output)
		}
	}
	if err := os.WriteFile(opts.output, []byte(saga), 0o600); err != nil {
		return err
	}
	_, _ = fmt.Fprintf(w, "✓ wrote %s\n\nNext:\n  draugr doctor %s   # check the scanners it needs\n  draugr scan %s\n",
		opts.output, opts.output, opts.output)
	return nil
}

// detect reports whether any of the given filenames exists in dir.
func detect(dir string, names ...string) bool {
	for _, n := range names {
		if _, err := os.Stat(filepath.Join(dir, n)); err == nil {
			return true
		}
	}
	return false
}

// scaffoldSaga renders a starter Saga, tuned by what it finds in dir.
func scaffoldSaga(dir, name string) string {
	isGo := detect(dir, "go.mod")
	hasDeps := isGo || detect(dir, "package.json", "requirements.txt", "pyproject.toml", "pom.xml", "Gemfile", "Cargo.toml", "composer.json")
	hasDocker := detect(dir, "Dockerfile")

	var b strings.Builder
	b.WriteString("# Generated by `draugr init`. Edit to taste, then: draugr scan draugr.saga.yaml\n")
	var detected []string
	if isGo {
		detected = append(detected, "Go")
	}
	if hasDeps {
		detected = append(detected, "dependency manifest")
	}
	if hasDocker {
		detected = append(detected, "Dockerfile")
	}
	if len(detected) > 0 {
		b.WriteString("# Detected: " + strings.Join(detected, ", ") + "\n")
	}
	fmt.Fprintf(&b, "release:\n  name: %s\n  version: \"0.0.0\"\n", name)
	b.WriteString("config:\n  controllers:\n")
	b.WriteString("    sca:\n      enabled: true       # dependency vulnerabilities (Trivy)\n")
	b.WriteString("    secrets:\n      enabled: true       # leaked credentials (Gitleaks)\n")
	b.WriteString("    sast:\n      enabled: true       # code security (Semgrep)\n")
	if isGo {
		b.WriteString("      scanners: [semgrep, gosec]   # Go detected — gosec adds Go-specific checks\n")
	}
	b.WriteString("    iac:\n      enabled: true       # IaC misconfiguration (Trivy config)\n")
	if hasDocker {
		b.WriteString("    # images:\n    #   enabled: true     # container CVEs (Trivy) — add your built image below\n")
	}
	fmt.Fprintf(&b, "components:\n  - name: %s\n    repositories:\n      - url: .\n", name)
	if hasDocker {
		b.WriteString("    # images:\n    #   - image: myorg/" + name + ":latest\n")
	}
	b.WriteString("    # hosts:            # for the headers/DAST controls\n")
	b.WriteString("    #   - name: api\n    #     url: https://api.example.com\n    #     type: api\n")
	return b.String()
}
