package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/draugr-dev/draugr/internal/version"
	"github.com/draugr-dev/draugr/pkg/saga"
)

type initOptions struct {
	// fragment writes a Saga fragment rather than a Saga.
	fragment bool
	output   string
	force    bool
}

func newInitCommand() *cobra.Command {
	opts := &initOptions{}
	cmd := &cobra.Command{
		Use:   "init [dir]",
		Short: "Scaffold a draugr.saga.yaml for the current project",
		Long: "Write a starter Saga for the given directory (default: the current one),\n" +
			"detecting the stack to pre-fill sensible controls. Edit it, then `draugr scan`.\n" +
			"For an instant scan with no file, use `draugr scan .` instead.\n\n" +
			"--fragment writes a Saga fragment instead: one component, no release and no policy,\n" +
			"for a descriptor assembled from several files. The component is named after the\n" +
			"directory; fragments naming the same component merge into one.\n\n" +
			"  draugr init services/payments --fragment\n" +
			"  draugr init services/payments --fragment -o azure.saga-fragment.yaml",
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			if opts.fragment && !cmd.Flags().Changed("output") {
				opts.output = filepath.Join(dir, "draugr.saga-fragment.yaml")
			}
			return runInit(dir, *opts, cmd.OutOrStdout())
		},
	}
	cmd.Flags().StringVarP(&opts.output, "output", "o", "draugr.saga.yaml", "path to write the Saga (- for stdout)")
	cmd.Flags().BoolVarP(&opts.force, "force", "f", false, "overwrite an existing file")
	cmd.Flags().BoolVar(&opts.fragment, "fragment", false,
		"write a Saga fragment (a component, no release or policy) instead of a Saga")
	return cmd
}

// runInit scaffolds a Saga for dir, writing it to opts.output (or stdout).
func runInit(dir string, opts initOptions, w io.Writer) error {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	name := filepath.Base(abs)
	if name == "" || name == "." || name == string(filepath.Separator) {
		name = "app"
	}
	body := scaffoldSaga(dir, name)
	if opts.fragment {
		body = scaffoldFragment(name)
	}
	saga := body

	if opts.output == "-" {
		_, err := io.WriteString(w, saga)
		return err
	}
	if !opts.force {
		if _, err := os.Stat(opts.output); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", opts.output)
		}
	}
	if err := os.WriteFile(opts.output, []byte(saga), 0o600); err != nil {
		return err
	}
	if opts.fragment {
		// A fragment is not scannable on its own — it has no release and no controls. Pointing at
		// `draugr scan` here would send someone to an error the tool could have avoided.
		_, _ = fmt.Fprintf(w, "✓ wrote %s\n\nNext, name it from a descriptor:\n"+
			"  fragments:\n    - path: \"**/%s\"\n\n"+
			"  draugr validate <saga> --resolved   # see the merged result\n",
			opts.output, filepath.Base(opts.output))
		return nil
	}
	_, _ = fmt.Fprintf(w, "✓ wrote %s\n\nNext:\n  draugr doctor %s   # check the scanners it needs\n  draugr scan %s\n",
		opts.output, opts.output, opts.output)
	return nil
}

// detect reports whether any of the given filenames exists in dir.
// depManifest names the file that made the dependency check apply, because "dependency manifest"
// is a category and the reader is looking at a directory. Naming the file they can see turns a
// comment they have to translate into one they can check.
func depManifest(dir string) string {
	for _, name := range []string{
		"go.mod", "package.json", "requirements.txt", "pyproject.toml",
		"pom.xml", "Gemfile", "Cargo.toml", "composer.json",
	} {
		if detect(dir, name) {
			return name
		}
	}
	return "a lockfile"
}

func detect(dir string, names ...string) bool {
	for _, n := range names {
		if _, err := os.Stat(filepath.Join(dir, n)); err == nil {
			return true
		}
	}
	return false
}

// scaffoldSaga renders a starter Saga, tuned by what it finds in dir.
func scaffoldSaga(dir, name string) string {
	isGo := detect(dir, "go.mod")
	hasDeps := isGo || detect(dir, "package.json", "requirements.txt", "pyproject.toml", "pom.xml", "Gemfile", "Cargo.toml", "composer.json")
	hasDocker := detect(dir, "Dockerfile")

	var b strings.Builder
	// The modeline gives editors schema-driven completion, hover docs and validation with no
	// setup: the YAML language server (VS Code, JetBrains, Neovim) fetches it on open.
	// Pin the schema to this build's version, so the scaffolded file is validated against the
	// same rules the binary that wrote it enforces. Swap it for saga.SchemaURL to track latest,
	// or for a local path from `draugr schema -o …` to drop the network dependency entirely.
	b.WriteString("# yaml-language-server: $schema=" + saga.SchemaURLFor(version.Version) + "\n")
	b.WriteString("# Generated by `draugr init`. Edit to taste, then: draugr scan draugr.saga.yaml\n")
	var detected []string
	if isGo {
		detected = append(detected, "Go")
	}
	if hasDeps {
		detected = append(detected, "dependencies to scan ("+depManifest(dir)+")")
	}
	if hasDocker {
		detected = append(detected, "Dockerfile")
	}
	if len(detected) > 0 {
		b.WriteString("# Detected: " + strings.Join(detected, ", ") + "\n")
	}
	fmt.Fprintf(&b, "release:\n  name: %s\n  version: \"0.0.0\"\n", name)
	b.WriteString("config:\n  controllers:\n")
	b.WriteString("    sca:\n      enabled: true       # dependency vulnerabilities (Trivy)\n")
	b.WriteString("    secrets:\n      enabled: true       # leaked credentials (Gitleaks)\n")
	b.WriteString("    sast:\n      enabled: true       # code security (Semgrep)\n")
	if isGo {
		b.WriteString("      gosec:\n        enabled: true   # Go detected — gosec adds Go-specific checks\n")
	}
	b.WriteString("    iac:\n      enabled: true       # IaC misconfiguration (Trivy config)\n")
	if hasDocker {
		b.WriteString("    # images:\n    #   enabled: true     # container CVEs (Trivy) — add your built image below\n")
	}
	fmt.Fprintf(&b, "components:\n  - name: %s\n    repositories:\n      - url: .\n", name)
	if hasDocker {
		b.WriteString("    # images:\n    #   - image: myorg/" + name + ":latest\n")
	}
	b.WriteString("    # hosts:            # for the headers/DAST controls\n")
	b.WriteString("    #   - name: api\n    #     url: https://api.example.com\n    #     type: api\n")
	return b.String()
}

// scaffoldFragment writes a starter Saga fragment for one component.
//
// Much smaller than a Saga's scaffold, and necessarily so: `init` detects a stack to pre-fill
// `config.controllers`, and a fragment may not carry controllers — policy stays in the descriptor
// that names it. What is left is the part worth automating anyway: the modeline, which is long
// and silently wrong if mistyped, and the component name.
//
// The name comes from the directory because it is the field that has to match across a
// component's fragments. A shared fragment and a per-cloud one agreeing on it is what makes them
// merge into one component instead of two.
func scaffoldFragment(name string) string {
	var b strings.Builder
	b.WriteString("# yaml-language-server: $schema=" + saga.FragmentSchemaURL + "\n")
	b.WriteString("# A Saga fragment: merged into any descriptor whose `fragments:` matches this file.\n")
	b.WriteString("# It may declare components and exclusions. Policy — the gate, which controls run —\n")
	b.WriteString("# stays in the descriptor that names it, where a reviewer sees it.\n\n")
	b.WriteString("components:\n")
	b.WriteString("  - name: " + name + "\n")
	b.WriteString("    # exposure and criticality belong in the shared fragment: where two fragments\n")
	b.WriteString("    # describe one component, the first description of a field wins.\n")
	b.WriteString("    # exposure: internal        # public | authenticated | internal | restricted\n")
	b.WriteString("    # criticality: important    # critical | important | supporting\n")
	b.WriteString("    repositories:\n")
	b.WriteString("      - url: .\n")
	return b.String()
}
