package cli

import (
	"fmt"
	"io"
	"path"
	"slices"
	"strings"

	"github.com/draugr-dev/draugr/internal/inventory"
	"github.com/draugr-dev/draugr/internal/manifests"
	"github.com/draugr-dev/draugr/internal/version"
	"github.com/draugr-dev/draugr/pkg/saga"
	"github.com/draugr-dev/draugr/pkg/tui"
)

// shownPaths caps a comment's list of paths; the rest are counted.
const shownPaths = 3

// pathList joins paths with a separator, the first shownPaths of them and a count of the rest.
func pathList(paths []string) string {
	if len(paths) > shownPaths {
		return strings.Join(paths[:shownPaths], " · ") + fmt.Sprintf(" · +%d", len(paths)-shownPaths)
	}
	return strings.Join(paths, " · ")
}

func filePaths(files []manifests.File) []string {
	out := make([]string, len(files))
	for i, f := range files {
		out[i] = f.Path
	}
	return out
}

// goModules names the go.mod files a tree's Go directories hold.
func goModules(t inventory.Tree) []string {
	out := make([]string, len(t.Go))
	for i, d := range t.Go {
		out[i] = path.Join(d, "go.mod")
	}
	return out
}

// iacInputs are what the iac control reads in a tree: Terraform, Helm, Kubernetes and Dockerfiles.
func iacInputs(t inventory.Tree) []string {
	var out []string
	out = append(out, t.Terraform...)
	out = append(out, t.Helm...)
	out = append(out, t.Kubernetes...)
	out = append(out, t.Dockerfiles...)
	return out
}

// trivyUnreadNames are the distinct file names in TrivyUnread, for the reason a comment gives.
func trivyUnreadNames(t inventory.Tree) string {
	var names []string
	for _, f := range t.TrivyUnread {
		if n := path.Base(f.Path); !slices.Contains(names, n) {
			names = append(names, n)
		}
	}
	return strings.Join(names, " or ")
}

// scaffoldSaga renders a starter Saga for what the tree holds.
func scaffoldSaga(t inventory.Tree, name string, perDirectory bool) string {
	// note appends the paths behind a line to its comment, so the reason a control is on can be
	// checked against the tree.
	note := func(s string) string {
		if s == "" {
			return ""
		}
		return " · " + s
	}
	var b strings.Builder
	// The modeline gives editors schema-driven completion, hover docs and validation with no
	// setup: the YAML language server (VS Code, JetBrains, Neovim) fetches it on open.
	// Pin the schema to this build's version, so the scaffolded file is validated against the
	// same rules the binary that wrote it enforces.
	b.WriteString("# yaml-language-server: $schema=" + saga.SchemaURLFor(version.Version) + "\n")
	b.WriteString("# Generated by `draugr init`. Edit to taste, then: draugr scan draugr.saga.yaml\n")
	// The project at the top level, which is the only place it is named. A descriptor Draugr wrote
	// itself must be one Draugr's own next command accepts.
	fmt.Fprintf(&b, "project: %s\n", name)
	b.WriteString("config:\n")
	if len(t.Go) > 0 {
		fmt.Fprintf(&b, "  reachability:\n    analyzers: [govulncheck]   # ranks a Go finding down when no code calls it%s\n",
			note(pathList(goModules(t))))
	}
	b.WriteString("  controls:\n")
	b.WriteString("    sca:\n      enabled: true       # dependency vulnerabilities (Trivy)\n")
	if len(t.VendoredJS) > 0 {
		fmt.Fprintf(&b, "      retirejs:\n        enabled: true     # copied JavaScript no lockfile lists%s\n",
			note(pathList(t.VendoredJS)))
	}
	if len(t.TrivyUnread) > 0 {
		fmt.Fprintf(&b, "      grypeFs:\n        enabled: true     # Trivy does not read %s%s\n",
			trivyUnreadNames(t), note(pathList(filePaths(t.TrivyUnread))))
	}
	b.WriteString("    secrets:\n      enabled: true       # leaked credentials (Gitleaks)\n")
	b.WriteString("    sast:\n      enabled: true       # code security (Semgrep)\n")
	if len(t.Go) > 0 {
		fmt.Fprintf(&b, "      gosec:\n        enabled: true     # Go-specific checks%s\n", note(pathList(goModules(t))))
	}
	fmt.Fprintf(&b, "    iac:\n      enabled: true       # IaC misconfiguration (Trivy config)%s\n", note(pathList(iacInputs(t))))
	if len(t.Dockerfiles) > 0 {
		b.WriteString("    # images:\n    #   enabled: true     # container CVEs (Trivy). Add your built image below\n")
	}

	b.WriteString("components:\n")
	if perDirectory && len(t.Parts) > 0 {
		writePerDirectory(&b, t, name)
		return b.String()
	}
	fmt.Fprintf(&b, "  - name: %s\n    repositories:\n      - url: .\n", name)
	writeUnresolvedComment(&b, t.Unresolved)
	if len(t.Parts) > 0 {
		fmt.Fprintf(&b, "    # Directories with their own dependency files: %s\n", pathList(t.Parts))
		b.WriteString("    # `draugr init --per-directory` writes a component for each.\n")
	}
	writeSurfaceStubs(&b, t, name)
	return b.String()
}

// writeSurfaceStubs comments out the images and hosts a component may declare, pre-filled from a
// Dockerfile and an OpenAPI document where the tree holds one.
func writeSurfaceStubs(b *strings.Builder, t inventory.Tree, name string) {
	if len(t.Dockerfiles) > 0 {
		b.WriteString("    # images:\n    #   - image: myorg/" + name + ":latest\n")
	}
	b.WriteString("    # hosts:            # for the headers/DAST controls\n")
	b.WriteString("    #   - name: api\n    #     url: https://api.example.com\n    #     type: api\n")
	if len(t.OpenAPI) > 0 {
		fmt.Fprintf(b, "    #     spec:\n    #       path: ./%s\n", t.OpenAPI[0])
	}
}

// writeUnresolvedComment names the dependency files no scanner can take packages from.
func writeUnresolvedComment(b *strings.Builder, unresolved []manifests.Unread) {
	for _, u := range unresolved {
		fmt.Fprintf(b, "    # Unread · %s %s · its packages are not checked\n", u.Path, u.Reason)
	}
}

// writePerDirectory writes the root component and one component per part, each scoped by paths:
// and each part carved out of the components above it by ignore:.
func writePerDirectory(b *strings.Builder, t inventory.Tree, project string) {
	names := componentNames(t.Parts, project)
	fmt.Fprintf(b, "  - name: %s\n    repositories:\n      - url: .\n        ignore: [%s]\n", project, dirList(topParts(t.Parts)))
	writeUnresolvedFor(b, t.Unresolved, ".", t.Parts)
	writeSurfaceStubs(b, t, project)
	for _, p := range t.Parts {
		fmt.Fprintf(b, "  - name: %s\n    repositories:\n      - url: .\n        paths: [%s]\n", names[p], p)
		if inner := beneath(p, t.Parts); len(inner) > 0 {
			fmt.Fprintf(b, "        ignore: [%s]\n", dirList(inner))
		}
		writeUnresolvedFor(b, t.Unresolved, p, t.Parts)
	}
}

// writeUnresolvedFor comments the unresolved files that belong to part dir: beneath it, and not
// beneath a part nested inside it.
func writeUnresolvedFor(b *strings.Builder, unresolved []manifests.Unread, dir string, parts []string) {
	var mine []manifests.Unread
	for _, u := range unresolved {
		if owner(u.Path, parts) == dir {
			mine = append(mine, u)
		}
	}
	writeUnresolvedComment(b, mine)
}

// owner is the deepest part holding rel, or "." for the root.
func owner(rel string, parts []string) string {
	best := "."
	for _, p := range parts {
		if strings.HasPrefix(rel, p+"/") && len(p) > len(best) {
			best = p
		}
	}
	return best
}

// topParts are the parts not beneath another part.
func topParts(parts []string) []string {
	var out []string
	for _, p := range parts {
		if owner(p, parts) == "." {
			out = append(out, p)
		}
	}
	return out
}

// beneath are the parts directly nested in dir.
func beneath(dir string, parts []string) []string {
	var out []string
	for _, p := range parts {
		if strings.HasPrefix(p, dir+"/") && owner(p, parts) == dir {
			out = append(out, p)
		}
	}
	return out
}

func dirList(dirs []string) string {
	out := make([]string, len(dirs))
	for i, d := range dirs {
		out[i] = d + "/"
	}
	return strings.Join(out, ", ")
}

// componentNames names each part after its directory, and after its whole path where two parts
// share a directory name or one shares the project's.
func componentNames(parts []string, project string) map[string]string {
	count := map[string]int{project: 1}
	for _, p := range parts {
		count[projectNameFrom(path.Base(p))]++
	}
	out := map[string]string{}
	for _, p := range parts {
		n := projectNameFrom(path.Base(p))
		if count[n] > 1 {
			n = projectNameFrom(p)
		}
		out[p] = n
	}
	return out
}

// foundRow is one kind of thing found, where, and what it enabled.
type foundRow struct{ kind, where, enables string }

func foundRows(t inventory.Tree) []foundRow {
	var rows []foundRow
	byEco := map[string][]string{}
	var ecos []string
	for _, f := range t.Dependencies {
		if _, ok := byEco[f.Ecosystem]; !ok {
			ecos = append(ecos, f.Ecosystem)
		}
		byEco[f.Ecosystem] = append(byEco[f.Ecosystem], f.Path)
	}
	for _, e := range ecos {
		enables := "sca"
		if e == "go" {
			enables = "sca · gosec · govulncheck"
		}
		rows = append(rows, foundRow{e, pathList(byEco[e]), enables})
	}
	if len(t.VendoredJS) > 0 {
		rows = append(rows, foundRow{"copied JavaScript", pathList(t.VendoredJS), "retirejs"})
	}
	if len(t.TrivyUnread) > 0 {
		rows = append(rows, foundRow{"read by Grype only", pathList(filePaths(t.TrivyUnread)), "grype-fs"})
	}
	if len(t.Terraform) > 0 {
		rows = append(rows, foundRow{"Terraform", pathList(t.Terraform), "iac"})
	}
	if len(t.Helm) > 0 {
		rows = append(rows, foundRow{"Helm", pathList(t.Helm), "iac"})
	}
	if len(t.Kubernetes) > 0 {
		rows = append(rows, foundRow{"Kubernetes", pathList(t.Kubernetes), "iac"})
	}
	if len(t.Dockerfiles) > 0 {
		rows = append(rows, foundRow{"Dockerfile", pathList(t.Dockerfiles), "iac · images, commented"})
	}
	if len(t.OpenAPI) > 0 {
		rows = append(rows, foundRow{"OpenAPI", pathList(t.OpenAPI), "hosts spec, commented"})
	}
	return rows
}

// unreadNote says what the Unread section lists, in the words a scan's own section uses.
const initUnreadNote = "dependency files no scanner can take packages from · their packages will not be checked"

// writeInitSummary prints what init wrote and what needs a person.
func writeInitSummary(w io.Writer, col tui.Painter, t inventory.Tree, opts initOptions) {
	out := opts.output
	_, _ = fmt.Fprintf(w, "%s wrote %s\n", col.Paint(tui.StylePass, "✓"), out)
	if opts.perDirectory && len(t.Parts) == 0 {
		_, _ = fmt.Fprintf(w, "  --per-directory: no directory below the root holds its own dependency file · wrote one component\n")
	}
	_, _ = fmt.Fprintln(w)

	if rows := foundRows(t); len(rows) > 0 {
		_, _ = fmt.Fprintln(w, col.Paint(tui.StyleMuted, "FOUND"))
		tbl := tui.NewTable(col).Indent("  ")
		for _, r := range rows {
			tbl.Row(tui.PlainCell(r.kind), tui.PlainCell(r.where), tui.Styled(tui.StyleMuted, r.enables))
		}
		tbl.Render(w)
		_, _ = fmt.Fprintln(w)
	}
	if len(t.Unresolved) > 0 {
		_, _ = fmt.Fprintln(w, col.Paint(tui.StyleMuted, "UNREAD")+"  "+col.Paint(tui.StyleMuted, initUnreadNote))
		width := 0
		for _, u := range t.Unresolved {
			width = max(width, len(u.Path))
		}
		for _, u := range t.Unresolved {
			_, _ = fmt.Fprintf(w, "  %-*s  %s\n", width, u.Path, col.Paint(tui.StyleMuted, string(u.Reason)))
		}
		_, _ = fmt.Fprintln(w)
	}
	_, _ = fmt.Fprintf(w, "Next:\n  draugr doctor %s   # check the scanners it needs\n  draugr scan %s\n", out, out)
}
