package cli

import (
	"fmt"
	"io"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/draugr-dev/draugr/pkg/saga"
)

// printResolved writes the descriptor as it stands after every fragment has been merged.
//
// The answer to a question composition creates: once a descriptor is assembled from several
// files, opening one of them no longer tells you what is in force. A tool whose first principle
// is that nothing fails silently should not ship the assembly without the means to inspect the
// result.
//
// Provenance is emitted as YAML comments, which makes the output both the human answer and a
// valid descriptor — comments are ignored by the decoder, so the flattened document can be
// scanned. That is what lets a resolved descriptor cross an air gap, be committed as a lockfile
// with every remote revision pinned to the commit it resolved to, or be diffed in CI so a
// one-line `fragments:` change is reviewed by its effect rather than by its cause.
func printResolved(w io.Writer, res *saga.Resolved) error {
	// The references are spent: everything they named is already in the model below. Leaving
	// them in would make the output re-resolve when scanned — appending every exclusion a second
	// time, and failing outright wherever the fragments are not reachable, which is precisely the
	// air-gapped case this output exists to serve.
	flat := *res.Model
	flat.Fragments = nil

	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(saga.Indent)
	if err := enc.Encode(&flat); err != nil {
		return fmt.Errorf("render resolved descriptor: %w", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("render resolved descriptor: %w", err)
	}

	if _, err := fmt.Fprint(w, resolvedHeader(res)); err != nil {
		return err
	}
	_, err := fmt.Fprint(w, buf.String())
	return err
}

// resolvedHeader lists what was merged, so the sources are stated once at the top rather than
// repeated against every block they contributed.
//
// A remote source shows the revision the descriptor asked for and the commit it resolved to. A
// tag that moves produces the same descriptor with a different commit, and this line is where
// that becomes visible.
func resolvedHeader(res *saga.Resolved) string {
	var b strings.Builder
	b.WriteString("# Resolved Saga — every fragment merged. Generated by `draugr validate --resolved`.\n")
	b.WriteString("# Valid input: comments are the provenance, so this can be scanned as it stands.\n")
	b.WriteString("#\n")
	for _, s := range res.Sources {
		switch {
		case s.Root:
			_, _ = fmt.Fprintf(&b, "# root:     %s\n", s.Path)
		case s.URL == "":
			_, _ = fmt.Fprintf(&b, "# fragment: %s\n", s.Path)
		default:
			_, _ = fmt.Fprintf(&b, "# fragment: %s\n", s)
		}
	}
	if len(res.Sources) == 1 {
		b.WriteString("#\n# (no fragments — this descriptor stands alone)\n")
	}
	b.WriteString("\n")
	return b.String()
}
