#!/usr/bin/env python3
"""Generate a hash-pinned requirements file for a Python-packaged scanner.

    python3 internal/tools/pythonpins/generate.py semgrep 1.173.0

Writes internal/tools/pythonpins/<tool>.txt: every package in the resolved tree with the SHA-256
PyPI publishes for the artifact chosen on this platform, in the form `pip install --require-hashes`
demands.

Generated rather than hand-maintained. A bump is a regenerated file and a diff somebody reads, not
sixty-six lines edited by hand — and a hand-edited hash is one nobody can check.

WHAT THIS PINS, AND WHAT IT DOES NOT. Resolution happens on the machine that runs this, so the
wheels chosen are this platform's and this Python's. That is why installation falls back to an
unpinned resolve elsewhere rather than failing: a pin that only holds on the maintainer's laptop
would otherwise make the tool uninstallable everywhere else. The fallback says so at install time.
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    tool, version = sys.argv[1], sys.argv[2]
    out = Path(__file__).parent / f"{tool}.txt"

    with tempfile.TemporaryDirectory() as tmp:
        venv = Path(tmp) / "venv"
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
        pip = venv / "bin" / "pip"
        subprocess.run([str(pip), "install", "--quiet", "--upgrade", "pip"], check=True)

        report = Path(tmp) / "report.json"
        subprocess.run(
            [str(pip), "install", "--dry-run", "--quiet", "--report", str(report),
             f"{tool}=={version}"],
            check=True,
        )
        resolved = json.loads(report.read_text())["install"]

    lines, missing = [], []
    for pkg in sorted(resolved, key=lambda p: p["metadata"]["name"].lower()):
        name = pkg["metadata"]["name"]
        ver = pkg["metadata"]["version"]
        hashes = pkg.get("download_info", {}).get("archive_info", {}).get("hashes", {})
        digest = hashes.get("sha256")
        if not digest:
            missing.append(name)
            continue
        lines.append(f"{name}=={ver} \\\n    --hash=sha256:{digest}")

    if missing:
        # A package with no publisher hash cannot be pinned, and a requirements file that quietly
        # omits one pins less than it appears to.
        print(f"no sha256 from PyPI for: {', '.join(missing)}", file=sys.stderr)
        return 1

    header = (
        f"# Generated by internal/tools/pythonpins/generate.py — do not edit.\n"
        f"#\n"
        f"# {tool} {version}, resolved on {sys.platform} with Python "
        f"{sys.version_info.major}.{sys.version_info.minor}.\n"
        f"# Every hash is the one PyPI publishes for the artifact chosen on that platform, so an\n"
        f"# install elsewhere may need a different wheel and will say so rather than pretend.\n"
        f"#\n"
        f"# Regenerate:  python3 internal/tools/pythonpins/generate.py {tool} <version>\n"
    )
    out.write_text(header + "\n" + "\n".join(lines) + "\n")
    print(f"{out}: {len(lines)} packages pinned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
