// Package scaffold renders the starter Saga `draugr init` writes for a source tree.
//
// It holds the part of init that decides what a descriptor says, and none of what writes it or
// prints a summary, so every caller that proposes a descriptor for a directory proposes the same
// one: the CLI writes it to a file, and the MCP server returns it for an assistant to show.
package scaffold

import (
	"fmt"
	"path"
	"slices"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/draugr-dev/draugr/internal/inventory"
	"github.com/draugr-dev/draugr/internal/manifests"
	"github.com/draugr-dev/draugr/internal/version"
	"github.com/draugr-dev/draugr/pkg/saga"
)

// shownPaths caps a comment's list of paths; the rest are counted.
const shownPaths = 3

// PathList joins paths with a separator, the first shownPaths of them and a count of the rest.
func PathList(paths []string) string {
	if len(paths) > shownPaths {
		return strings.Join(paths[:shownPaths], " · ") + fmt.Sprintf(" · +%d", len(paths)-shownPaths)
	}
	return strings.Join(paths, " · ")
}

// FilePaths are the paths of files, in order.
func FilePaths(files []manifests.File) []string {
	out := make([]string, len(files))
	for i, f := range files {
		out[i] = f.Path
	}
	return out
}

// GoModules names the go.mod files a tree's Go directories hold.
func GoModules(t inventory.Tree) []string {
	out := make([]string, len(t.Go))
	for i, d := range t.Go {
		out[i] = path.Join(d, "go.mod")
	}
	return out
}

// iacInputs are what the iac control reads in a tree: Terraform, Helm, Kubernetes and Dockerfiles.
func iacInputs(t inventory.Tree) []string {
	var out []string
	out = append(out, t.Terraform...)
	out = append(out, t.Helm...)
	out = append(out, t.Kubernetes...)
	out = append(out, t.Dockerfiles...)
	return out
}

// trivyUnreadNames are the distinct file names in TrivyUnread, for the reason a comment gives.
func trivyUnreadNames(t inventory.Tree) string {
	var names []string
	for _, f := range t.TrivyUnread {
		if n := path.Base(f.Path); !slices.Contains(names, n) {
			names = append(names, n)
		}
	}
	return strings.Join(names, " or ")
}

// The trivyFs.filePatterns that point Trivy's pip analyzer at a requirements file it does not open
// by name. Trivy matches each regex against the path relative to the scan root.
const (
	// pipNamedPattern reaches a .txt whose name holds "requirements": requirements-dev.txt,
	// dev-requirements.txt.
	pipNamedPattern = `pip:requirements[^/]*\.txt$`
	// pipDirPattern reaches a .txt directly under a directory named requirements.
	pipDirPattern = `pip:(^|/)requirements/[^/]+\.txt$`
)

// pipFilePatterns are the patterns that reach the requirements files in TrivyByPattern, one for
// each way a requirements file is named.
func pipFilePatterns(t inventory.Tree) []string {
	var named, inDir bool
	for _, f := range t.TrivyByPattern {
		if strings.Contains(path.Base(f.Path), "requirements") {
			named = true
		} else {
			inDir = true
		}
	}
	var out []string
	if named {
		out = append(out, pipNamedPattern)
	}
	if inDir {
		out = append(out, pipDirPattern)
	}
	return out
}

// yamlStrings renders a flow sequence of single-quoted strings, which YAML reads without escapes,
// so a regex's backslashes are written once.
func yamlStrings(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = "'" + strings.ReplaceAll(s, "'", "''") + "'"
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// Saga renders a starter Saga for what the tree holds.
func Saga(t inventory.Tree, name string, perDirectory bool) string {
	// note appends the paths behind a line to its comment, so the reason a control is on can be
	// checked against the tree.
	note := func(s string) string {
		if s == "" {
			return ""
		}
		return " · " + s
	}
	var b strings.Builder
	// The modeline gives editors schema-driven completion, hover docs and validation with no
	// setup: the YAML language server (VS Code, JetBrains, Neovim) fetches it on open.
	// Pin the schema to this build's version, so the scaffolded file is validated against the
	// same rules the binary that wrote it enforces.
	b.WriteString("# yaml-language-server: $schema=" + saga.SchemaURLFor(version.Version) + "\n")
	b.WriteString("# Generated by `draugr init`. Edit to taste, then: draugr scan draugr.saga.yaml\n")
	// The project at the top level, which is the only place it is named. A descriptor Draugr wrote
	// itself must be one Draugr's own next command accepts.
	fmt.Fprintf(&b, "project: %s\n", Scalar(name))
	b.WriteString("config:\n")
	if len(t.Go) > 0 {
		fmt.Fprintf(&b, "  reachability:\n    analyzers: [govulncheck]   # ranks a Go finding down when no code calls it%s\n",
			note(PathList(GoModules(t))))
	}
	b.WriteString("  controls:\n")
	b.WriteString("    sca:\n      enabled: true       # dependency vulnerabilities (Trivy)\n")
	if patterns := pipFilePatterns(t); len(patterns) > 0 {
		fmt.Fprintf(&b, "      trivyFs:\n        filePatterns: %s   # requirements files under other names%s\n",
			yamlStrings(patterns), note(PathList(FilePaths(t.TrivyByPattern))))
	}
	if len(t.VendoredJS) > 0 {
		fmt.Fprintf(&b, "      retirejs:\n        enabled: true     # copied JavaScript, outside any lockfile%s\n",
			note(PathList(t.VendoredJS)))
	}
	if len(t.TrivyUnread) > 0 {
		fmt.Fprintf(&b, "      grypeFs:\n        enabled: true     # Trivy does not read %s%s\n",
			trivyUnreadNames(t), note(PathList(FilePaths(t.TrivyUnread))))
	}
	b.WriteString("    secrets:\n      enabled: true       # leaked credentials (Gitleaks)\n")
	b.WriteString("    sast:\n      enabled: true       # code security (Semgrep)\n")
	if len(t.Go) > 0 {
		fmt.Fprintf(&b, "      gosec:\n        enabled: true     # Go-specific checks%s\n", note(PathList(GoModules(t))))
	}
	fmt.Fprintf(&b, "    iac:\n      enabled: true       # IaC misconfiguration (Trivy config)%s\n", note(PathList(iacInputs(t))))
	if len(t.Dockerfiles) > 0 {
		b.WriteString("    # images:\n    #   enabled: true     # container CVEs (Trivy). Add your built image below\n")
	}

	b.WriteString("components:\n")
	if perDirectory && len(t.Parts) > 0 {
		writePerDirectory(&b, t, name)
		return b.String()
	}
	fmt.Fprintf(&b, "  - name: %s\n    repositories:\n      - url: .\n", Scalar(name))
	writeUnresolvedComment(&b, t.Unresolved)
	if len(t.Parts) > 0 {
		fmt.Fprintf(&b, "    # Directories with their own dependency files: %s\n", PathList(t.Parts))
		b.WriteString("    # `draugr init --per-directory` writes a component for each.\n")
	}
	writeSurfaceStubs(&b, t, name)
	return b.String()
}

// writeSurfaceStubs comments out the images and hosts a component may declare, pre-filled from a
// Dockerfile and an OpenAPI document where the tree holds one.
func writeSurfaceStubs(b *strings.Builder, t inventory.Tree, name string) {
	if len(t.Dockerfiles) > 0 {
		b.WriteString("    # images:\n    #   - image: myorg/" + name + ":latest\n")
	}
	b.WriteString("    # hosts:            # for the headers/DAST controls\n")
	b.WriteString("    #   - name: api\n    #     url: https://api.example.com\n    #     type: api\n")
	if len(t.OpenAPI) > 0 {
		fmt.Fprintf(b, "    #     spec:\n    #       path: ./%s\n", t.OpenAPI[0])
	}
}

// writeUnresolvedComment names the dependency files no scanner can take packages from.
func writeUnresolvedComment(b *strings.Builder, unresolved []manifests.Unread) {
	for _, u := range unresolved {
		fmt.Fprintf(b, "    # Unread · %s %s · its packages are not checked\n", u.Path, u.Reason)
	}
}

// writePerDirectory writes the root component and one component per part, each scoped by paths:
// and each part carved out of the components above it by ignore:.
func writePerDirectory(b *strings.Builder, t inventory.Tree, project string) {
	names := componentNames(t.Parts, project)
	fmt.Fprintf(b, "  - name: %s\n    repositories:\n      - url: .\n        ignore: [%s]\n", Scalar(project), dirList(topParts(t.Parts)))
	writeUnresolvedFor(b, t.Unresolved, ".", t.Parts)
	writeSurfaceStubs(b, t, project)
	for _, p := range t.Parts {
		fmt.Fprintf(b, "  - name: %s\n    repositories:\n      - url: .\n        paths: [%s]\n", Scalar(names[p]), Scalar(p))
		if inner := beneath(p, t.Parts); len(inner) > 0 {
			fmt.Fprintf(b, "        ignore: [%s]\n", dirList(inner))
		}
		writeUnresolvedFor(b, t.Unresolved, p, t.Parts)
	}
}

// writeUnresolvedFor comments the unresolved files that belong to part dir: beneath it, and not
// beneath a part nested inside it.
func writeUnresolvedFor(b *strings.Builder, unresolved []manifests.Unread, dir string, parts []string) {
	var mine []manifests.Unread
	for _, u := range unresolved {
		if owner(u.Path, parts) == dir {
			mine = append(mine, u)
		}
	}
	writeUnresolvedComment(b, mine)
}

// owner is the deepest part holding rel, or "." for the root.
func owner(rel string, parts []string) string {
	best := "."
	for _, p := range parts {
		if strings.HasPrefix(rel, p+"/") && len(p) > len(best) {
			best = p
		}
	}
	return best
}

// topParts are the parts not beneath another part.
func topParts(parts []string) []string {
	var out []string
	for _, p := range parts {
		if owner(p, parts) == "." {
			out = append(out, p)
		}
	}
	return out
}

// beneath are the parts directly nested in dir.
func beneath(dir string, parts []string) []string {
	var out []string
	for _, p := range parts {
		if strings.HasPrefix(p, dir+"/") && owner(p, parts) == dir {
			out = append(out, p)
		}
	}
	return out
}

func dirList(dirs []string) string {
	out := make([]string, len(dirs))
	for i, d := range dirs {
		out[i] = Scalar(d + "/")
	}
	return strings.Join(out, ", ")
}

// componentNames names each part after its directory, and after its whole path where two parts
// share a directory name or one shares the project's.
func componentNames(parts []string, project string) map[string]string {
	count := map[string]int{project: 1}
	for _, p := range parts {
		count[ProjectName(path.Base(p))]++
	}
	out := map[string]string{}
	for _, p := range parts {
		n := ProjectName(path.Base(p))
		if count[n] > 1 {
			n = ProjectName(p)
		}
		out[p] = n
	}
	return out
}

// Scalar is s as a YAML scalar that reads back as the same string, in a block mapping or inside a
// flow sequence: bare where it would, double-quoted where YAML would read it as a number, a
// boolean or null (2024, 1e3, 0x10, true) or where it holds a character that means something in
// YAML. Names and paths come from directory names, which can be any of these.
//
// The YAML 1.1 booleans are quoted too, because an editor's parser may read yes and on as true,
// and the schema then rejects the value.
func Scalar(s string) string {
	switch s {
	case "y", "n", "yes", "no", "on", "off":
		return strconv.Quote(s)
	}
	var v []any
	if err := yaml.Unmarshal([]byte("["+s+"]"), &v); err == nil && len(v) == 1 {
		if got, ok := v[0].(string); ok && got == s {
			return s
		}
	}
	return strconv.Quote(s)
}

// ProjectName turns a directory name into one a descriptor accepts.
//
// Lowercase letters, digits and dashes, starting and ending with a letter or digit, which is what
// `pkg/saga` enforces. Anything else becomes a dash, runs of dashes collapse, and the ends are
// trimmed. A name with nothing usable left in it, which a directory of punctuation or of
// non-Latin script produces, falls back to the same placeholder an unnamed directory gets: a
// scaffold somebody renames beats one that will not load.
func ProjectName(dir string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(dir) {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	name := strings.Trim(b.String(), "-")
	for strings.Contains(name, "--") {
		name = strings.ReplaceAll(name, "--", "-")
	}
	// The rule wants a letter or digit at each end, and the trim above leaves one there or leaves
	// nothing at all.
	if name == "" {
		return "app"
	}
	return name
}
